package model;
// Generated 26.Nis.2017 08:51:20 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Travel generated by hbm2java
 */
@Entity
@Table(name="travel"
    ,catalog="dp"
)
public class Travel  implements java.io.Serializable {


     private Integer travelid;
     private Users users;
     private String place;
     private String goal;
     private Date startdate;
     private Date finishdate;
     private Integer cost;
     private String information;
     private String codepr;

    public Travel() {
    }

	
    public Travel(Users users, String place, String goal, Date startdate, Date finishdate, String codepr) {
        this.users = users;
        this.place = place;
        this.goal = goal;
        this.startdate = startdate;
        this.finishdate = finishdate;
        this.codepr = codepr;
    }
    public Travel(Users users, String place, String goal, Date startdate, Date finishdate, Integer cost, String information, String codepr) {
       this.users = users;
       this.place = place;
       this.goal = goal;
       this.startdate = startdate;
       this.finishdate = finishdate;
       this.cost = cost;
       this.information = information;
       this.codepr = codepr;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="travelid", unique=true, nullable=false)
    public Integer getTravelid() {
        return this.travelid;
    }
    
    public void setTravelid(Integer travelid) {
        this.travelid = travelid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="place", nullable=false, length=45)
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }

    
    @Column(name="goal", nullable=false, length=75)
    public String getGoal() {
        return this.goal;
    }
    
    public void setGoal(String goal) {
        this.goal = goal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="startdate", nullable=false, length=10)
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="finishdate", nullable=false, length=10)
    public Date getFinishdate() {
        return this.finishdate;
    }
    
    public void setFinishdate(Date finishdate) {
        this.finishdate = finishdate;
    }

    
    @Column(name="cost")
    public Integer getCost() {
        return this.cost;
    }
    
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    
    @Column(name="information", length=60)
    public String getInformation() {
        return this.information;
    }
    
    public void setInformation(String information) {
        this.information = information;
    }

    
    @Column(name="codepr", nullable=false, length=8)
    public String getCodepr() {
        return this.codepr;
    }
    
    public void setCodepr(String codepr) {
        this.codepr = codepr;
    }




}


