package model;
// Generated 21.�ub.2017 22:47:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Userroles generated by hbm2java
 */
@Entity
@Table(name="userroles"
    ,catalog="dp"
    , uniqueConstraints = @UniqueConstraint(columnNames={"role", "username"}) 
)
public class Userroles  implements java.io.Serializable {


     private Integer userroleid;
     private Users users;
     private String role;

    public Userroles() {
    }

    public Userroles(Users users, String role) {
       this.users = users;
       this.role = role;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="userroleid", unique=true, nullable=false)
    public Integer getUserroleid() {
        return this.userroleid;
    }
    
    public void setUserroleid(Integer userroleid) {
        this.userroleid = userroleid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="role", nullable=false, length=45)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


